### ISSUE TITLE
Connection refused when running "./interactive-benchmark.sh"

### ISSUE THREAD

**Issue by Li-Rong-Gang** [thu-pacman/LiveGraph-Binary#3]
Hi there,
I'm encountering an issue when trying to run "./interactive-benchmark.sh" of SNB.I followed the installation instructions in the README file,but I get the following error message:
```
Parameters:
	Name:                           LDBC-SNB
	DB:                             com.ldbc.impls.workloads.ldbc.snb.livegraph.interactive.LiveGraphDb
	Workload:                       com.ldbc.driver.workloads.ldbc.snb.interactive.LdbcSnbInteractiveWorkload
	Operation Count:                4,800,000
	Warmup Count:                   0
	Skip Count:                     0
	Worker Threads:                 48
	Status Display Interval:        00:01.000 (m:s.ms)
	Time Unit:                      MICROSECONDS
	Results Directory:              /home/user/lrg/ldbc/LiveGraph-Binary/SNB/driver/results
	Time Compression Ratio:         0.0010000
	Validation Creation Params:     null
	Database Validation File:       null
	Calculate Workload Statistics:  false
	Spinner Sleep Duration:         00:00.001 (m:s.ms) / 1 (ms)
	Print Help:                     false
	Ignore Scheduled Start Times:   true
	User-defined parameters:
		hostname = localhost
		ldbc.snb.interactive.LdbcQuery10_enable = true
		ldbc.snb.interactive.LdbcQuery10_freq = 35
		ldbc.snb.interactive.LdbcQuery11_enable = true
		ldbc.snb.interactive.LdbcQuery11_freq = 19
		ldbc.snb.interactive.LdbcQuery12_enable = true
		ldbc.snb.interactive.LdbcQuery12_freq = 44
		ldbc.snb.interactive.LdbcQuery13_enable = true
		ldbc.snb.interactive.LdbcQuery13_freq = 19
		ldbc.snb.interactive.LdbcQuery14_enable = true
		ldbc.snb.interactive.LdbcQuery14_freq = 49
		ldbc.snb.interactive.LdbcQuery1_enable = true
		ldbc.snb.interactive.LdbcQuery1_freq = 26
		ldbc.snb.interactive.LdbcQuery2_enable = true
		ldbc.snb.interactive.LdbcQuery2_freq = 37
		ldbc.snb.interactive.LdbcQuery3_enable = true
		ldbc.snb.interactive.LdbcQuery3_freq = 92
		ldbc.snb.interactive.LdbcQuery4_enable = true
		ldbc.snb.interactive.LdbcQuery4_freq = 36
		ldbc.snb.interactive.LdbcQuery5_enable = true
		ldbc.snb.interactive.LdbcQuery5_freq = 66
		ldbc.snb.interactive.LdbcQuery6_enable = true
		ldbc.snb.interactive.LdbcQuery6_freq = 236
		ldbc.snb.interactive.LdbcQuery7_enable = true
		ldbc.snb.interactive.LdbcQuery7_freq = 54
		ldbc.snb.interactive.LdbcQuery8_enable = true
		ldbc.snb.interactive.LdbcQuery8_freq = 15
		ldbc.snb.interactive.LdbcQuery9_enable = true
		ldbc.snb.interactive.LdbcQuery9_freq = 287
		ldbc.snb.interactive.LdbcShortQuery1PersonProfile_enable = true
		ldbc.snb.interactive.LdbcShortQuery2PersonPosts_enable = true
		ldbc.snb.interactive.LdbcShortQuery3PersonFriends_enable = true
		ldbc.snb.interactive.LdbcShortQuery4MessageContent_enable = true
		ldbc.snb.interactive.LdbcShortQuery5MessageCreator_enable = true
		ldbc.snb.interactive.LdbcShortQuery6MessageForum_enable = true
		ldbc.snb.interactive.LdbcShortQuery7MessageReplies_enable = true
		ldbc.snb.interactive.LdbcUpdate1AddPerson_enable = true
		ldbc.snb.interactive.LdbcUpdate2AddPostLike_enable = true
		ldbc.snb.interactive.LdbcUpdate3AddCommentLike_enable = true
		ldbc.snb.interactive.LdbcUpdate4AddForum_enable = true
		ldbc.snb.interactive.LdbcUpdate5AddForumMembership_enable = true
		ldbc.snb.interactive.LdbcUpdate6AddPost_enable = true
		ldbc.snb.interactive.LdbcUpdate7AddComment_enable = true
		ldbc.snb.interactive.LdbcUpdate8AddFriendship_enable = true
		ldbc.snb.interactive.gct_delta_duration = 10000
		ldbc.snb.interactive.max_write_event_start_time = 1364478634915
		ldbc.snb.interactive.min_write_event_start_time = 1347528960010
		ldbc.snb.interactive.num_events = 36368766
		ldbc.snb.interactive.parameters_dir = /home/user/lrg/ldbc/LiveGraph-Binary/SNB/datagen/substitution_parameters
		ldbc.snb.interactive.short_read_dissipation = 0.2
		ldbc.snb.interactive.update_interleave = 466
		ldbc.snb.interactive.updates_dir = /home/user/lrg/ldbc/LiveGraph-Binary/SNB/datagen/social_network
		peer_identifiers = 
		port = 9090
		results_log = true

ExecuteWorkloadMode  
 ---------------------------------
 --- No Warmup Phase Requested ---
 ---------------------------------
ExecuteWorkloadMode  
 -----------------
 --- Run Phase ---
 -----------------
ExecuteWorkloadMode  Scanning workload streams to calculate their limits...
WorkloadStreams  Scanned 0 of 0 - OFFSET
WorkloadStreams  Scanned 1,000,000 of 4,800,000 - RUN
WorkloadStreams  Scanned 2,000,000 of 4,800,000 - RUN
WorkloadStreams  Scanned 4,800,000 of 4,800,000 - RUN
ExecuteWorkloadMode  Loaded workload: com.ldbc.driver.workloads.ldbc.snb.interactive.LdbcSnbInteractiveWorkload
ExecuteWorkloadMode  Retrieving workload stream: LdbcSnbInteractiveWorkload
org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused (Connection refused)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:226)
	at com.ldbc.impls.workloads.ldbc.snb.livegraph.interactive.LiveGraphDbConnectionState.<init>(LiveGraphDbConnectionState.java:25)
	at com.ldbc.impls.workloads.ldbc.snb.livegraph.interactive.LiveGraphDb.onInit(LiveGraphDb.java:21)
	at com.ldbc.driver.Db.init(Db.java:34)
	at com.ldbc.driver.client.ExecuteWorkloadMode.doInit(ExecuteWorkloadMode.java:233)
	at com.ldbc.driver.client.ExecuteWorkloadMode.startExecutionAndAwaitCompletion(ExecuteWorkloadMode.java:131)
	at com.ldbc.driver.Client.main(Client.java:53)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:221)
	... 6 more


```
I'm not sure what's causing this error or how to fix it. In addition,I want to know where is "snb_server" in "TZ=UTC ./snb_server LIVEGRAPH_DATAPATH $LiveGraphSNB/datagen/social_network 9090" ? Is this file generated by "./interactive-benchmark.sh"?

**Comment by jiguanglizipao** [comment]
`snb_server` can be downloaded from https://github.com/thu-pacman/LiveGraph-Binary/releases/tag/20200829

**Comment by Li-Rong-Gang** [comment]
> `snb_server` can be downloaded from https://github.com/thu-pacman/LiveGraph-Binary/releases/tag/20200829

Thank you very much!
And I meet another problem. When I try to start snb server, I got a segment fault.
`neu@iZ0jlfjo2yxee61gy5z0dxZ:/mnt2/neu/yusong/code/LiveGraph-Binary/SNB$ mkdir -p LIVEGRAPH_DATAPATH
neu@iZ0jlfjo2yxee61gy5z0dxZ:/mnt2/neu/yusong/code/LiveGraph-Binary/SNB$ TZ=UTC ./snb_server LIVEGRAPH_DATAPATH $LiveGraphSNB/datagen/social_network 9090
Finish prepareVIndex
Segmentation fault`
How can I check the cause of this fault?

**Comment by Li-Rong-Gang** [comment]
> `snb_server` can be downloaded from https://github.com/thu-pacman/LiveGraph-Binary/releases/tag/20200829

Thank you very much!
And I meet another problem. When I try to start snb server, I got a segment fault.
`
neu@iZ0jlfjo2yxee61gy5z0dxZ:/mnt2/neu/yusong/code/LiveGraph-Binary/SNB$ mkdir -p LIVEGRAPH_DATAPATH neu@iZ0jlfjo2yxee61gy5z0dxZ:/mnt2/neu/yusong/code/LiveGraph-Binary/SNB$ TZ=UTC ./snb_server LIVEGRAPH_DATAPATH $LiveGraphSNB/datagen/social_network 9090 
Finish prepareVIndex 
Segmentation fault
`
How can I check the cause of this fault?

**Comment by jiguanglizipao** [comment]
Have you generated the SNB data into `$LiveGraphSNB/datagen` by following https://github.com/thu-pacman/LiveGraph-Binary/tree/master/SNB#usage?

**Comment by Li-Rong-Gang** [comment]
> Have you generated the SNB data into `$LiveGraphSNB/datagen` by following https://github.com/thu-pacman/LiveGraph-Binary/tree/master/SNB#usage?

Yes , and I get two data directory, social_network and substitution_parameters.
`
neu@iZ0jlfjo2yxee61gy5z0dxZ:/mnt2/neu/yusong/code/LiveGraph-Binary/SNB/datagen/social_network$ ls
comment_0_0.csv                 organisation_0_0.csv               person_likes_comment_0_0.csv         place_0_0.csv            tagclass_isSubclassOf_tagclass_0_0.csv
comment_hasTag_tag_0_0.csv      person_0_0.csv                     person_likes_post_0_0.csv            post_0_0.csv             tag_hasType_tagclass_0_0.csv
forum_0_0.csv                   person_email_emailaddress_0_0.csv  person_speaks_language_0_0.csv       post_hasTag_tag_0_0.csv  updateStream_0_0_forum.csv
forum_hasMember_person_0_0.csv  person_hasInterest_tag_0_0.csv     person_studyAt_organisation_0_0.csv  tag_0_0.csv              updateStream_0_0_person.csv
forum_hasTag_tag_0_0.csv        person_knows_person_0_0.csv        person_workAt_organisation_0_0.csv   tagclass_0_0.csv         updateStream.properties
neu@iZ0jlfjo2yxee61gy5z0dxZ:/mnt2/neu/yusong/code/LiveGraph-Binary/SNB/datagen/social_network$ cd ..
neu@iZ0jlfjo2yxee61gy5z0dxZ:/mnt2/neu/yusong/code/LiveGraph-Binary/SNB/datagen$ cd substitution_parameters/
neu@iZ0jlfjo2yxee61gy5z0dxZ:/mnt2/neu/yusong/code/LiveGraph-Binary/SNB/datagen/substitution_parameters$ ls
interactive_10_param.txt  interactive_12_param.txt  interactive_14_param.txt  interactive_2_param.txt  interactive_4_param.txt  interactive_6_param.txt  interactive_8_param.txt
interactive_11_param.txt  interactive_13_param.txt  interactive_1_param.txt   interactive_3_param.txt  interactive_5_param.txt  interactive_7_param.txt  interactive_9_param.txt
`

**Comment by jiguanglizipao** [comment]
What about environment variable $LiveGraphSNB, e.g., ls $LiveGraphSNB/datagen/social_network 2023年5月26日 13:27，Lrg ***@***.***>写道：

Have you generated the SNB data into $LiveGraphSNB/datagen by following https://github.com/thu-pacman/LiveGraph-Binary/tree/master/SNB#usage?

Yes , and I get two data directory, social_network and substitution_parameters.
***@***.***:/mnt2/neu/yusong/code/LiveGraph-Binary/SNB/datagen/social_network$ ls comment_0_0.csv                 organisation_0_0.csv               person_likes_comment_0_0.csv         place_0_0.csv            tagclass_isSubclassOf_tagclass_0_0.csv comment_hasTag_tag_0_0.csv      person_0_0.csv                     person_likes_post_0_0.csv            post_0_0.csv             tag_hasType_tagclass_0_0.csv forum_0_0.csv                   person_email_emailaddress_0_0.csv  person_speaks_language_0_0.csv       post_hasTag_tag_0_0.csv  updateStream_0_0_forum.csv forum_hasMember_person_0_0.csv  person_hasInterest_tag_0_0.csv     person_studyAt_organisation_0_0.csv  tag_0_0.csv              updateStream_0_0_person.csv forum_hasTag_tag_0_0.csv        person_knows_person_0_0.csv        person_workAt_organisation_0_0.csv   tagclass_0_0.csv         updateStream.properties ***@***.***:/mnt2/neu/yusong/code/LiveGraph-Binary/SNB/datagen/social_network$ cd .. ***@***.***:/mnt2/neu/yusong/code/LiveGraph-Binary/SNB/datagen$ cd substitution_parameters/ ***@***.***:/mnt2/neu/yusong/code/LiveGraph-Binary/SNB/datagen/substitution_parameters$ ls interactive_10_param.txt  interactive_12_param.txt  interactive_14_param.txt  interactive_2_param.txt  interactive_4_param.txt  interactive_6_param.txt  interactive_8_param.txt interactive_11_param.txt  interactive_13_param.txt  interactive_1_param.txt   interactive_3_param.txt  interactive_5_param.txt  interactive_7_param.txt  interactive_9_param.txt

**Comment by Li-Rong-Gang** [comment]
@jiguanglizipao Yes, I have set the $LiveGraphSNB
As you can see , this is the path in interactive-benchmark.properties
`
#SNB data path
ldbc.snb.interactive.parameters_dir=/mnt2/neu/yusong/code/LiveGraph-Binary/SNB/datagen/substitution_parameters
ldbc.snb.interactive.updates_dir=/mnt2/neu/yusong/code/LiveGraph-Binary/SNB/datagen/social_network
ldbc.snb.interactive.short_read_dissipation=0.2

`
And there have been some files imported into LIVEGRAPH_DATAPATH:
`
neu@iZ0jlfjo2yxee61gy5z0dxZ:/mnt2/neu/yusong/code/LiveGraph-Binary/SNB$ cd LIVEGRAPH_DATAPATH/
neu@iZ0jlfjo2yxee61gy5z0dxZ:/mnt2/neu/yusong/code/LiveGraph-Binary/SNB/LIVEGRAPH_DATAPATH$ ls
000003.log  000077.sst  000112.sst  000120.sst  000127.sst  IDENTITY
000069.sst  000079.sst  000113.sst  000121.sst  000128.sst  LOCK
000071.sst  000093.sst  000114.sst  000122.sst  000129.sst  LOG
000073.sst  000094.sst  000115.sst  000123.sst  000130.sst  MANIFEST-000004
000074.sst  000100.sst  000117.sst  000124.sst  CURRENT     OPTIONS-000052

`
By the way, this process just use 2% of the memory .And I just have a executable file:"snb_server" , so I can't debug it to know why I get segment fault.

**Comment by Li-Rong-Gang** [comment]
Yes, I have set the $LiveGraphSNB
As you can see , this is the path in interactive-benchmark.properties
`
#SNB data path
ldbc.snb.interactive.parameters_dir=/mnt2/neu/yusong/code/LiveGraph-Binary/SNB/datagen/substitution_parameters
ldbc.snb.interactive.updates_dir=/mnt2/neu/yusong/code/LiveGraph-Binary/SNB/datagen/social_network
ldbc.snb.interactive.short_read_dissipation=0.2
`
And there have been some files imported into LIVEGRAPH_DATAPATH:
`
neu@iZ0jlfjo2yxee61gy5z0dxZ:/mnt2/neu/yusong/code/LiveGraph-Binary/SNB$ cd LIVEGRAPH_DATAPATH/
neu@iZ0jlfjo2yxee61gy5z0dxZ:/mnt2/neu/yusong/code/LiveGraph-Binary/SNB/LIVEGRAPH_DATAPATH$ ls
000003.log 000077.sst 000112.sst 000120.sst 000127.sst IDENTITY
000069.sst 000079.sst 000113.sst 000121.sst 000128.sst LOCK
000071.sst 000093.sst 000114.sst 000122.sst 000129.sst LOG
000073.sst 000094.sst 000115.sst 000123.sst 000130.sst MANIFEST-000004
000074.sst 000100.sst 000117.sst 000124.sst CURRENT OPTIONS-000052
`
By the way, this process just use 2% of the memory .And I just have a executable file:"snb_server" , so I can't debug it to know why I get segment fault.

**Comment by Li-Rong-Gang** [comment]
Yes, I have set the $LiveGraphSNB
And there have been some files imported into LIVEGRAPH_DATAPATH:
`
user/LiveGraph-Binary/SNB$ cd LIVEGRAPH_DATAPATH/ 
user/LiveGraph-Binary/SNB/LIVEGRAPH_DATAPATH$ ls 
000003.log 000077.sst 000112.sst 000120.sst 000127.sst IDENTITY 000069.sst 000079.sst 000113.sst 000121.sst 000128.sst LOCK 000071.sst 000093.sst 000114.sst 000122.sst 000129.sst LOG 000073.sst 000094.sst 000115.sst 000123.sst 000130.sst MANIFEST-000004 000074.sst 000100.sst 000117.sst 000124.sst CURRENT OPTIONS-000052
`
By the way, this process just use 2% of the memory .And I just have a executable file:"snb_server" , so I can't debug it to know why I get segment fault.

**Comment by jiguanglizipao** [comment]
Here are code of `snb_server` and `ldbc_snb_implementations`
https://github.com/TriCache-OSDI-AE/LiveGraph-snb/tree/master
https://github.com/TriCache-OSDI-AE/ldbc_snb_implementations

**Comment by Li-Rong-Gang** [comment]
@jiguanglizipao Thank you very much for your help, and through the source code I find that the schema is different between snb_server and social_network. Like, in tag_0_0.csv, the scheme is "id|name|url" but in snb_server it is "id|name|url|hasType".

**Comment by Li-Rong-Gang** [comment]
It seems that the function like importTag not only import vertex tag but also import the edge. But the dataset tag_0_0.csv has no column named hasType. Is there a problem with my dataset generation?

> @jiguanglizipao Thank you very much for your help, and through the source code I find that the schema is different between snb_server and social_network. Like, in tag_0_0.csv, the scheme is "id|name|url" but in snb_server it is "id|name|url|hasType".

**Comment by jiguanglizipao** [comment]
It needs a CsvCompositeMergeForeign Dataset by setting the params.ini. Here is an example.

# Using CsvCompositeMergeForeign Mode
ldbc.snb.datagen.serializer.dynamicActivitySerializer:ldbc.snb.datagen.serializer.snb.csv.dynamicserializer.activity.CsvCompositeMergeForeignDynamicActivitySerializer
ldbc.snb.datagen.serializer.dynamicPersonSerializer:ldbc.snb.datagen.serializer.snb.csv.dynamicserializer.person.CsvCompositeMergeForeignDynamicPersonSerializer
ldbc.snb.datagen.serializer.staticSerializer:ldbc.snb.datagen.serializer.snb.csv.staticserializer.CsvCompositeMergeForeignStaticSerializer

# Setting update streams and scale Factor
ldbc.snb.datagen.serializer.numUpdatePartitions:16
ldbc.snb.datagen.generator.scaleFactor:snb.interactive.300
